import { Provider, BlogPost } from "@/types";

export const mockProviders: Provider[] = [
  {
    id: "1",
    name: "AVL List GmbH",
    slug: "avl-list",
    description:
      "AVL ist das weltweit größte unabhängige Unternehmen für die Entwicklung, Simulation und das Testen von Antriebssystemen. Mit KI-gestützten Lösungen optimieren wir Entwicklungsprozesse für die Mobilität der Zukunft.",
    short_description: "Weltmarktführer in KI-gestützter Antriebssystementwicklung",
    website: "https://www.avl.com",
    email: "ki@avl.com",
    categories: ["KI-Entwicklung", "Machine Learning", "Datenanalyse"],
    tags: ["Automotive", "Simulation", "F&E"],
    verified: true,
    featured: true,
    rating: 4.8,
    review_count: 24,
    created_at: "2024-01-01",
  },
  {
    id: "2",
    name: "Anton Paar GmbH",
    slug: "anton-paar",
    description:
      "Anton Paar entwickelt und produziert hochpräzise Labor- und Prozessmesstechnik sowie Rheometer. Unsere KI-Lösungen automatisieren Messprozesse und steigern die Qualitätssicherung in der Industrie.",
    short_description: "Präzisionsmesstechnik mit KI-gestützter Prozessoptimierung",
    website: "https://www.anton-paar.com",
    email: "ki@anton-paar.com",
    categories: ["Prozessautomatisierung", "Datenanalyse"],
    tags: ["Messtechnik", "Qualitätssicherung", "Labor"],
    verified: true,
    featured: true,
    rating: 4.7,
    review_count: 18,
    created_at: "2024-01-15",
  },
  {
    id: "3",
    name: "DataMind Graz",
    slug: "datamind-graz",
    description:
      "DataMind Graz ist ein spezialisiertes KI-Beratungsunternehmen, das KMUs in der Steiermark bei der digitalen Transformation unterstützt. Von der Strategie bis zur Implementierung – wir begleiten Sie auf Ihrem KI-Weg.",
    short_description: "KI-Beratung für KMUs in der Steiermark",
    website: "https://datamind-graz.at",
    email: "info@datamind-graz.at",
    phone: "+43 316 123 456",
    categories: ["KI-Beratung", "Machine Learning"],
    tags: ["KMU", "Beratung", "Digitalisierung"],
    verified: true,
    featured: false,
    rating: 4.9,
    review_count: 31,
    created_at: "2024-02-01",
  },
  {
    id: "4",
    name: "VisionAI Steiermark",
    slug: "visionai-steiermark",
    description:
      "Spezialisiert auf Computer Vision und Bildverarbeitung für die Industrie. Wir entwickeln maßgeschneiderte Lösungen für Qualitätskontrolle, Sicherheitssysteme und automatisierte Inspektion.",
    short_description: "Computer Vision & Bildverarbeitung für die Industrie",
    email: "office@visionai-stmk.at",
    categories: ["Computer Vision", "KI-Entwicklung"],
    tags: ["Bildverarbeitung", "Qualitätskontrolle", "Industrie"],
    verified: true,
    featured: false,
    rating: 4.6,
    review_count: 12,
    created_at: "2024-02-15",
  },
  {
    id: "5",
    name: "NLP Solutions Austria",
    slug: "nlp-solutions-austria",
    description:
      "Wir entwickeln intelligente Sprachverarbeitungslösungen für den deutschsprachigen Raum. Chatbots, Dokumentenanalyse und automatisierte Textverarbeitung – immer auf Deutsch optimiert.",
    short_description: "Deutsche NLP-Lösungen: Chatbots & Dokumentenanalyse",
    email: "kontakt@nlp-austria.at",
    website: "https://nlp-austria.at",
    categories: ["Natural Language Processing", "KI-Entwicklung"],
    tags: ["Chatbot", "Deutsch", "Dokumentenanalyse"],
    verified: true,
    featured: false,
    rating: 4.5,
    review_count: 9,
    created_at: "2024-03-01",
  },
  {
    id: "6",
    name: "AutomateGraz",
    slug: "automate-graz",
    description:
      "AutomateGraz hilft Unternehmen dabei, repetitive Geschäftsprozesse durch KI zu automatisieren. Von der Rechnungsverarbeitung bis zur Kundenkorrespondenz – wir sparen Ihnen Zeit und Kosten.",
    short_description: "KI-Prozessautomatisierung für Ihr Unternehmen",
    email: "hallo@automategraz.at",
    phone: "+43 316 789 012",
    categories: ["Prozessautomatisierung", "KI-Tools & Software"],
    tags: ["Automatisierung", "RPA", "Effizienz"],
    verified: false,
    featured: false,
    rating: 4.3,
    review_count: 7,
    created_at: "2024-03-15",
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    id: "1",
    title: "Wie du deinen ersten KI-Chatbot für deine Website baust",
    slug: "ersten-ki-chatbot-website",
    excerpt:
      "Ein Schritt-für-Schritt-Guide für KMUs in der Steiermark, die KI-Chatbots ohne großes Budget einsetzen möchten.",
    content: "",
    author: "KI Graz Team",
    category: "Praxis-Guide",
    published_at: "2024-03-10",
    read_time: 8,
  },
  {
    id: "2",
    title: "75% Förderung für KI-Projekte: So beantragst du die Fördermittel",
    slug: "foerderung-ki-projekte-beantragen",
    excerpt:
      "Österreichische KMUs können bis zu 75% ihrer KI-Investitionen gefördert bekommen. Wir erklären wie.",
    content: "",
    author: "Förderexperte",
    category: "Förderungen",
    published_at: "2024-03-05",
    read_time: 6,
  },
  {
    id: "3",
    title: "KI in der steirischen Industrie: 5 Erfolgsgeschichten",
    slug: "ki-steirische-industrie-erfolgsgeschichten",
    excerpt:
      "Wie Grazer Unternehmen durch den Einsatz von KI ihre Produktivität um bis zu 40% steigern konnten.",
    content: "",
    author: "KI Graz Redaktion",
    category: "Erfolgsgeschichten",
    published_at: "2024-02-28",
    read_time: 10,
  },
];
